name: deploy

on:
  repository_dispatch:
    types: deploy
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Dependencies
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn build
      env:
        CI: true
    - uses: actions/upload-artifact@v1
      with:
        name: build-${{ github.sha }}
        path: build
    - name: Deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
#       with:
#         src: build/
#         dest: root@134.209.188.163:/var/www/massimopalmieri.it/public_html/
      with:
#         flags: '-avzr --delete'
#         options: ''
#         ssh_options: ''
        src: 'build/'
        dest: 'root@134.209.188.163:/var/www/massimopalmieri.it/public_html/'
    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"
